### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by ianbstewart** [Huffon/factsumm#36] opened 2023-07-19 17:36 UTC
I'm unable to reproduce the example on the README due to an error on the back-end with an `entities` key in the data. I installed via `pip`.

```
from factsumm import FactSumm
factsumm = FactSumm()
article = "Lionel Andrés Messi (born 24 June 1987) is an Argentine professional footballer who plays as a forward and captains both Spanish club Barcelona and the Argentina national team. Often considered as the best player in the world and widely regarded as one of the greatest players of all time, Messi has won a record six Ballon d'Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d'Or Dream Team."
summary = "Lionel Andrés Messi (born 24 Aug 1997) is an Spanish professional footballer who plays as a forward and captains both Spanish club Barcelona and the Spanish national team."
factsumm(article, summary, verbose=True)
```

Error:
```
Loading Named Entity Recognition Pipeline...
Loading Relation Extraction Pipeline...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/py3/lib/python3.8/site-packages/factsumm/__init__.py", line 360, in __call__
    source_ents, summary_ents, fact_score = self.extract_facts(
  File "/home/miniconda3/envs/py3/lib/python3.8/site-packages/factsumm/__init__.py", line 182, in extract_facts
    source_ents = self.ner(source_lines)
  File "/home/miniconda3/envs/py3/lib/python3.8/site-packages/factsumm/utils/level_entity.py", line 38, in extract_entities
    for entity in line_result["entities"]:
KeyError: 'entities'
```

**Comment by BiliBraker** [comment] 2023-07-20 05:59
I have experienced the exact same issue.

**Comment by DrZeydy** [comment] 2023-07-24 21:13
I was having the same issue.  Note that the code here does not have _level_entity.py_ (but I think it won't fix the issue if you pull the code directly from this repository).

In any case, the problem is that FLAIR seems to have changed their interface and now returns results in a different way.
In _extract_entities_, I had to change `line_result = sentence.to_dict(tag_type="ner")` to `line_result = sentence.get_spans('ner')`.  Also had to change the for loop under that code to:
`for entity in line_result:  <br>
       if entity.text not in cache: <br> 
                        dedup.append({ <br>
                            "word": entity.text, <br>
                            "entity": entity.tag, <br>
                            "start": entity.start_position, <br>
                            "end": entity.end_position, <br>
                        }) <br>
                        cache[entity.text] = None <br>
                result.append(dedup)`

**Comment by karter-liner** [comment] 2024-01-01 16:18
Thanks for reporting and suggesting corrected way to use FactSumm

FactSumm v0.1.4 Released!
Please check [release note](https://github.com/Huffon/factsumm/releases/tag/0.1.4)
We officially remove flair to prevent unstable dependency issue

**Closed as completed by karter-liner** 2024-01-01 16:18 UTC
